name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.6.1
      
      
    - name: Docker Login
  
  
      uses: docker/login-action@v3.3.0
      with:
    
        username: willian.zy6@gmail.com
   
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: Build and push Docker images
           
      uses: docker/build-push-action@v3.0.0
      with:
          # Build's context is the set of files located in the specified PATH or URL
        context: .
          # Path to the Dockerfile
        file: ./Dockerfile
          # Push is a shorthand for --output=type=registry
        push: true
          # List of tags
        tags: WillianZy/go_ci:${{github.ref_name}}
      